name: convo_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  provider: ^6.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8
  go_router: ^15.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  google_sign_in: ^6.3.0
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.6
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo/logo_app.jpg
    - assets/icons/
    - assets/images/
    - assets/icons/sports-svgrepo-com.svg
    - assets/icons/chat-computer-support-svgrepo-com.svg
    - assets/icons/movies-svgrepo-com.svg
    - assets/icons/books-and-people-svgrepo-com.svg
    - assets/icons/music-svgrepo-com.svg
    - assets/icons/travel-svgrepo-com.svg
    - assets/icons/gaming-pad-svgrepo-com.svg
    - assets/icons/food-and-drink-svgrepo-com.svg
