// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3VbWrx2r38AD0NXCJt2tN8e3g92Vteg',
    appId: '1:517937515610:web:7bff4cd021487be8cb1c63',
    messagingSenderId: '517937515610',
    projectId: 'convo-mate-927c5',
    authDomain: 'convo-mate-927c5.firebaseapp.com',
    storageBucket: 'convo-mate-927c5.firebasestorage.app',
    measurementId: 'G-XW77TG8VDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC464Q8yagQ_32CnqccseAEllp1qKG6mBU',
    appId: '1:517937515610:android:d7f5f16d67f882bccb1c63',
    messagingSenderId: '517937515610',
    projectId: 'convo-mate-927c5',
    storageBucket: 'convo-mate-927c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZKpTRGCpAA3R_2Q9xYwUJGdFucRwxjzA',
    appId: '1:517937515610:ios:7172710340cebd4ccb1c63',
    messagingSenderId: '517937515610',
    projectId: 'convo-mate-927c5',
    storageBucket: 'convo-mate-927c5.firebasestorage.app',
    iosBundleId: 'com.xtech.convoMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZKpTRGCpAA3R_2Q9xYwUJGdFucRwxjzA',
    appId: '1:517937515610:ios:7172710340cebd4ccb1c63',
    messagingSenderId: '517937515610',
    projectId: 'convo-mate-927c5',
    storageBucket: 'convo-mate-927c5.firebasestorage.app',
    iosBundleId: 'com.xtech.convoMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK3VbWrx2r38AD0NXCJt2tN8e3g92Vteg',
    appId: '1:517937515610:web:a957d640adda6ffdcb1c63',
    messagingSenderId: '517937515610',
    projectId: 'convo-mate-927c5',
    authDomain: 'convo-mate-927c5.firebaseapp.com',
    storageBucket: 'convo-mate-927c5.firebasestorage.app',
    measurementId: 'G-6Z4KHK17T9',
  );
}
